import { Button } from "./Button";
import { Text } from "./Text";

export const TemplateContent = () => {
  return (
    <div className="flex flex-col mx-5">
      <div className="h-16 flex items-center justify-end space-x-3">
        <Button variant="primary" size="sm">
          Edit
        </Button>
        <Button variant="danger" size="sm">
          Delete
        </Button>
      </div>

      <div className="w-full h-60 overflow-y-scroll">
        <Text size="sm" className="break-words">
          TEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTETEXTTEXTTEXTTEXTTEXTTEXTTE
        </Text>
      </div>
    </div>
  );
};
